### ISSUE TITLE
Index out of bounds exception

### ISSUE THREAD

**Issue by jmccrae** [ybyygu/rust-lbfgs#12]
I am getting this error

```
thread 'main' panicked at 'index out of bounds: the len is 74 but the index is 74', /home/jmccrae/.cargo/registry/src/github.com-1ecc6299db9ec823/liblbfgs-0.1.0/src/lbfgs.rs:538:27
```

It seems like the vector length is being calculated incorrectly?

**Comment by ybyygu** [comment]
How can I reproduce it? Can you provide a test?

**Comment by jmccrae** [comment]
See reproduction here: https://gist.github.com/jmccrae/167dd909cc32047f74237c3af7cc20b1

Sorry it is a bit long, the error was occurring randomly so I just found a failure and copied the code into a single file.

The original project is https://github.com/lod-cloud/lod-cloud-draw

**Comment by ybyygu** [comment]
Thank you for your feedback!

For your case, the end parameter was too large. I have commited a few changes to make sure these parameters are sound and
correct.

I am not sure if you really need enable OWL-QN algorithm. If not, please comment the ".with_orthantwise" line (line 429). I found, when OWL-QN algorithm disabled, your test passed without error.

**Comment by jmccrae** [comment]
Thanks for the speedy fix. 

I have been having some issues with the LBFGS implementation in that the line search keeps failing. This may be my code though so I will investigate further and create further issues when I understand the problem.
